export const TRUCK_PROBLEMS = [
  "Двигатель / система охлаждения / турбина",
  "Топливная система / ТНВД / форсунки",
  "Система выпуска",
  "КПП / сцепление",
  "Пневматика",
  "Тормозная система / колеса",
  "Шасси / подвеска",
  "Электрика / диагностика",
  "Отогреть / прикурить",
  "Кузовной ремонт",
  "Кондиционер / печка",
  "Другое",
];

export const TRUCK_BRANDS = [
  "Mercedes",
  "Scania",
  "MAN",
  "DAF",
  "Volvo",
  "Renault",
  "Ford",
  "МАЗ",
  "КамАЗ",
  //Китай
  "Dong Feng",
  "FAW",
  "FOTON",
  "HOWO",
  "Shacman",
  "SITRAK",
  "JAC",
  "Hongyan",
  "Hyundai",
  "Isuzu",
  "Mitsubishi",
  "Hino",
  "IVECO",
];

export const TRUCK_MODELS: { [code: string]: string[] } = {
  Mercedes: ["Actros", "Axor", "Arocs", "Atego"],
  Scania: ["Серия P", "Серия G", "Серия R", "Серия S"],
  MAN: ["TGA", "TGL", "TGX", "TGS", "TGM"],
  DAF: ["XF", "CF", "LF"],
  Volvo: ["FH", "FM", "FL", "FMX"],
  Renault: [
    "T",
    "Premium",
    "Midlum",
    "Magnum",
    "Kerax",
    "IVECO - Stralis",
    "Trakker",
    "EuroCargo",
  ],
  Ford: ["Cargo", "F-MAX"],
  КамАЗ: ["5490", "54901"],
};
