FROM python:3.11

EXPOSE 4001

WORKDIR /backend
COPY . /backend
WORKDIR /backend

# for the case if suddenly deployed venv
RUN rm -rf venv
RUN rm -rf .venv

RUN pip install pdm
RUN pdm sync

CMD ["pdm", "run", "python", "-m", "src.main_background"]