FROM python:3.11

EXPOSE 4002

WORKDIR /backend_telegram
COPY . /backend_telegram
WORKDIR /backend_telegram

# for the case if suddenly deployed venv
RUN rm -rf venv
RUN rm -rf .venv

RUN pip install pdm
RUN pdm sync

CMD ["pdm", "run", "python", "-m", "src.main_telegram"]