CREATE TABLE address
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    region_id  BIGINT,
    city       TEXT,
    street     TEXT,
    latitude   DOUBLE PRECISION,
    longtitude DOUBLE PRECISION,
    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE auto
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id  BIGINT,
    driver_id    BIGINT,
    brand        TEXT,
    model        TEXT,
    vin          TEXT,
    number       TEXT,
    is_merged    BOOLEAN                                 NOT NULL,
    merged_to_id BIGINT,
    type         TEXT                                    NOT NULL,
    CONSTRAINT pk_auto PRIMARY KEY (id)
);

CREATE TABLE country
(
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    CONSTRAINT pk_country PRIMARY KEY (code)
);

CREATE TABLE files
(
    code            TEXT   NOT NULL,
    location        TEXT   NOT NULL,
    filename        TEXT   NOT NULL,
    extension       TEXT   NOT NULL,
    content_type    TEXT   NOT NULL,
    type            TEXT   NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    user_id         BIGINT NOT NULL,
    create_at       BIGINT NOT NULL,
    CONSTRAINT pk_files PRIMARY KEY (code)
);

CREATE TABLE order_messages
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    guarantee_id          TEXT                                    NOT NULL,
    order_id              BIGINT                                  NOT NULL,
    user_id               BIGINT                                  NOT NULL,
    user_role             TEXT                                    NOT NULL,
    text                  TEXT,
    date                  BIGINT                                  NOT NULL,
    file_code             TEXT,
    is_viewed_by_master   BOOLEAN                                 NOT NULL,
    is_viewed_by_driver   BOOLEAN                                 NOT NULL,
    is_viewed_by_customer BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_order_messages PRIMARY KEY (id)
);

CREATE TABLE order_to_auto_assosiation
(
    auto_id  BIGINT NOT NULL,
    order_id BIGINT NOT NULL
);

CREATE TABLE orders
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    guarantee_uuid          TEXT                                    NOT NULL,
    customer_id             BIGINT,
    master_id               BIGINT,
    declined_masters_ids    TEXT,
    driver_id               BIGINT,
    created_at              BIGINT                                  NOT NULL,
    updated_at              BIGINT                                  NOT NULL,
    last_status_update_time BIGINT                                  NOT NULL,
    status                  TEXT                                    NOT NULL,
    description             TEXT,
    notes                   TEXT,
    address_id              BIGINT                                  NOT NULL,
    is_need_evacuator       BOOLEAN                                 NOT NULL,
    is_need_mobile_team     BOOLEAN                                 NOT NULL,
    urgency                 TEXT,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE orders_status_changes
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_at    BIGINT                                  NOT NULL,
    order_id      BIGINT                                  NOT NULL,
    new_status    TEXT                                    NOT NULL,
    updated_by_id BIGINT                                  NOT NULL,
    master_id     BIGINT,
    comment       TEXT,
    CONSTRAINT pk_orders_status_changes PRIMARY KEY (id)
);

CREATE TABLE region
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         TEXT,
    codes        TEXT,
    country_code TEXT,
    CONSTRAINT pk_region PRIMARY KEY (id)
);

CREATE TABLE tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    auto_id     BIGINT                                  NOT NULL,
    order_id    BIGINT                                  NOT NULL,
    name        TEXT                                    NOT NULL,
    description TEXT,
    price       DECIMAL(12, 2),
    created_at  BIGINT                                  NOT NULL,
    updated_at  BIGINT                                  NOT NULL,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

CREATE TABLE telegram_chats
(
    chat_uuid        TEXT   NOT NULL,
    telegram_chat_id BIGINT NOT NULL,
    title            TEXT,
    CONSTRAINT pk_telegram_chats PRIMARY KEY (chat_uuid)
);

CREATE TABLE user_info_changes
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    previous_name  TEXT                                    NOT NULL,
    new_name       TEXT                                    NOT NULL,
    previous_phone TEXT,
    new_phone      TEXT,
    previous_email TEXT,
    new_email      TEXT,
    previous_inn   TEXT,
    new_inn        TEXT,
    date           BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_info_changes PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role                        TEXT                                    NOT NULL,
    email                       TEXT,
    phone                       TEXT,
    balance                     DECIMAL(12, 2)                          NOT NULL,
    name                        TEXT                                    NOT NULL,
    inn                         TEXT,
    trip_radius_km              INTEGER,
    address_id                  BIGINT,
    registration_date           BIGINT                                  NOT NULL,
    password_hash               TEXT,
    password_creation_time      BIGINT,
    user_reset_code             TEXT,
    telegram_id                 BIGINT,
    telegram_access_error       TEXT,
    telegram_access_error_shown BOOLEAN,
    user_chats_codes            TEXT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE INDEX idx_users_telegram_id ON users (telegram_id);

ALTER TABLE address
    ADD CONSTRAINT FK_ADDRESS_ON_REGION FOREIGN KEY (region_id) REFERENCES region (id);

CREATE INDEX idx_address_region_id ON address (region_id);

ALTER TABLE auto
    ADD CONSTRAINT FK_AUTO_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES users (id);

ALTER TABLE auto
    ADD CONSTRAINT FK_AUTO_ON_DRIVER FOREIGN KEY (driver_id) REFERENCES users (id);

ALTER TABLE auto
    ADD CONSTRAINT FK_AUTO_ON_MERGED_TO FOREIGN KEY (merged_to_id) REFERENCES auto (id);

ALTER TABLE files
    ADD CONSTRAINT FK_FILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES address (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES users (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_DRIVER FOREIGN KEY (driver_id) REFERENCES users (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_MASTER FOREIGN KEY (master_id) REFERENCES users (id);

ALTER TABLE orders_status_changes
    ADD CONSTRAINT FK_ORDERS_STATUS_CHANGES_ON_MASTER FOREIGN KEY (master_id) REFERENCES users (id);

ALTER TABLE orders_status_changes
    ADD CONSTRAINT FK_ORDERS_STATUS_CHANGES_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE orders_status_changes
    ADD CONSTRAINT FK_ORDERS_STATUS_CHANGES_ON_UPDATED_BY FOREIGN KEY (updated_by_id) REFERENCES users (id);

ALTER TABLE order_messages
    ADD CONSTRAINT FK_ORDER_MESSAGES_ON_FILE_CODE FOREIGN KEY (file_code) REFERENCES files (code);

ALTER TABLE order_messages
    ADD CONSTRAINT FK_ORDER_MESSAGES_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_messages
    ADD CONSTRAINT FK_ORDER_MESSAGES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE region
    ADD CONSTRAINT FK_REGION_ON_COUNTRY_CODE FOREIGN KEY (country_code) REFERENCES country (code);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_AUTO FOREIGN KEY (auto_id) REFERENCES auto (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES address (id);

ALTER TABLE user_info_changes
    ADD CONSTRAINT FK_USER_INFO_CHANGES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE order_to_auto_assosiation
    ADD CONSTRAINT fk_ordtoautass_on_auto FOREIGN KEY (auto_id) REFERENCES auto (id);

ALTER TABLE order_to_auto_assosiation
    ADD CONSTRAINT fk_ordtoautass_on_order FOREIGN KEY (order_id) REFERENCES orders (id);