CREATE TABLE orders_notifications
(
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id                      BIGINT                                  NOT NULL,
    order_last_status_update_time BIGINT                                  NOT NULL,
    created_at                    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_orders_notifications PRIMARY KEY (id)
);

ALTER TABLE orders_notifications
    ADD CONSTRAINT FK_ORDERS_NOTIFICATIONS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);