CREATE TABLE transport_column
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    column_number       TEXT,
    CONSTRAINT pk_transport_column PRIMARY KEY (id)
);

CREATE TABLE driver
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name TEXT,
    phone TEXT,
    email TEXT,
    CONSTRAINT pk_driver PRIMARY KEY (id)
);

ALTER TABLE auto DROP CONSTRAINT FK_AUTO_ON_DRIVER;
ALTER TABLE auto RENAME TO transport;
ALTER TABLE order_to_auto_assosiation RENAME TO order_to_transport_assosiation;

ALTER TABLE order_to_transport_assosiation
    RENAME CONSTRAINT fk_ordtoautass_on_auto TO fk_ordtotransass_on_transport;
ALTER TABLE order_to_transport_assosiation
    RENAME CONSTRAINT fk_ordtoautass_on_order TO fk_ordtotransass_on_order;

ALTER TABLE order_to_transport_assosiation RENAME COLUMN auto_id TO transport_id;
ALTER TABLE tasks RENAME COLUMN auto_id TO transport_id;
ALTER TABLE transport RENAME CONSTRAINT FK_AUTO_ON_CUSTOMER TO FK_TRANSPORT_ON_CUSTOMER;
ALTER TABLE transport RENAME CONSTRAINT FK_AUTO_ON_MERGED_TO TO FK_TRANSPORT_ON_MERGED_TO;
ALTER TABLE tasks RENAME CONSTRAINT FK_TASKS_ON_AUTO TO FK_TASKS_ON_TRANSPORT;

ALTER TABLE transport
    ADD (
      transport_column_id BIGINT,
      main_transport_id BIGINT,
      park_number TEXT,
    );

ALTER TABLE transport
    ADD CONSTRAINT FK_TRANSPORT_ON_DRIVER FOREIGN KEY (driver_id) REFERENCES driver (id);
ALTER TABLE transport
    ADD CONSTRAINT FK_TRANSPORT_ON_TRANSPORT_COLUMN FOREIGN KEY (transport_column_id) REFERENCES transport_column (id);
ALTER TABLE transport
    ADD CONSTRAINT FK_TRANSPORT_TRAILER_ON_MAIN_TRANSPORT FOREIGN KEY (main_transport_id) REFERENCES transport (id);

ALTER TABLE orders DROP CONSTRAINT FK_ORDERS_ON_DRIVER;
ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_DRIVER FOREIGN KEY (driver_id) REFERENCES driver (id);


CREATE TABLE mechanic
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transport_column_id BIGINT,
    name TEXT,
    phone TEXT,
    email TEXT,
    CONSTRAINT pk_mechanic PRIMARY KEY (id)
);

ALTER TABLE mechanic
    ADD CONSTRAINT FK_MECHANIC_ON_TRANSPORT_COLUMN FOREIGN KEY (transport_column_id) REFERENCES transport_column (id);

CREATE TABLE document (
   id INT PRIMARY KEY  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   owner_transport_id BIGINT,
   owner_driver_id BIGINT,
   filename VARCHAR(255),
   filepath VARCHAR(500),
   uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE document
    ADD CONSTRAINT FK_DOCUMENT_ON_TRANSPORT_OWNER FOREIGN KEY (owner_transport_id) REFERENCES transport (id);

ALTER TABLE document
    ADD CONSTRAINT FK_DOCUMENT_ON_DRIVER_OWNER FOREIGN KEY (owner_driver_id) REFERENCES driver (id);

