"""add_order_status_change_comment

Revision ID: 02ea2b1ba2e7
Revises: e1d4c52f5c6c
Create Date: 2023-12-31 16:41:23.189845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02ea2b1ba2e7'
down_revision: Union[str, None] = 'e1d4c52f5c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_status_changes', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_status_changes', 'comment')
    # ### end Alembic commands ###
