"""add_country_to_region

Revision ID: 78083c32609d
Revises: a4399f99acc2
Create Date: 2023-12-24 17:56:00.592759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78083c32609d"
down_revision: Union[str, None] = "a4399f99acc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("region", sa.Column("country_code", sa.String(), nullable=True))
    op.create_foreign_key(None, "region", "country", ["country_code"], ["code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "region", type_="foreignkey") # type: ignore
    op.drop_column("region", "country_code")
    # ### end Alembic commands ###
