"""add_order_status_changes

Revision ID: e1d4c52f5c6c
Revises: 56d6d814a61c
Create Date: 2023-12-27 13:56:42.957596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e1d4c52f5c6c"
down_revision: Union[str, None] = "56d6d814a61c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders_status_changes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("new_status", sa.String(), nullable=False),
        sa.Column("updated_by_id", sa.Integer(), nullable=False),
        sa.Column("master_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["master_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_orders_status_changes_order_id"),
        "orders_status_changes",
        ["order_id"],
        unique=False,
    )
    op.drop_index("ix_order_status_changes_id", table_name="order_status_changes")
    op.drop_table("order_status_changes")
    op.create_index(
        op.f("ix_order_to_auto_assosiation_auto_id"),
        "order_to_auto_assosiation",
        ["auto_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_to_auto_assosiation_order_id"),
        "order_to_auto_assosiation",
        ["order_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_order_to_auto_assosiation_order_id"),
        table_name="order_to_auto_assosiation",
    )
    op.drop_index(
        op.f("ix_order_to_auto_assosiation_auto_id"),
        table_name="order_to_auto_assosiation",
    )
    op.create_table(
        "order_status_changes",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("time", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("order_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "previous_status",
            postgresql.ENUM(
                "CREATED",
                "CALCULATING",
                "REVIEWING",
                "ACCEPTED",
                "COMPLETED",
                "CANCELED",
                name="orderstatus",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "new_status",
            postgresql.ENUM(
                "CREATED",
                "CALCULATING",
                "REVIEWING",
                "ACCEPTED",
                "COMPLETED",
                "CANCELED",
                name="orderstatus",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "previous_master_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("new_master_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["new_master_id"],
            ["users.id"],
            name="order_status_changes_new_master_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name="order_status_changes_order_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["previous_master_id"],
            ["users.id"],
            name="order_status_changes_previous_master_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="order_status_changes_pkey"),
    )
    op.create_index(
        "ix_order_status_changes_id", "order_status_changes", ["id"], unique=False
    )
    op.drop_index(
        op.f("ix_orders_status_changes_order_id"), table_name="orders_status_changes"
    )
    op.drop_table("orders_status_changes")
    # ### end Alembic commands ###
