"""add_orders_indices

Revision ID: fec5dc4a33ca
Revises: b01f74628215
Create Date: 2023-12-18 21:55:53.530397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec5dc4a33ca'
down_revision: Union[str, None] = 'b01f74628215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_address_region_id'), 'address', ['region_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_address_region_id'), table_name='address')
    # ### end Alembic commands ###
