"""extend_order_status_enum

Revision ID: b01f74628215
Revises: 70bdb4862d82
Create Date: 2023-12-18 21:22:50.888541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b01f74628215'
down_revision: Union[str, None] = '70bdb4862d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE orderstatus ADD VALUE 'CANCELED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
