"""add_user_info_change

Revision ID: 70bdb4862d82
Revises: 25ed2f2dd807
Create Date: 2023-12-13 17:53:27.977608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70bdb4862d82'
down_revision: Union[str, None] = '25ed2f2dd807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('previous_name', sa.String(), nullable=False),
    sa.Column('new_name', sa.String(), nullable=False),
    sa.Column('previous_phone', sa.String(), nullable=True),
    sa.Column('new_phone', sa.String(), nullable=True),
    sa.Column('previous_email', sa.String(), nullable=True),
    sa.Column('new_email', sa.String(), nullable=True),
    sa.Column('previous_inn', sa.String(), nullable=True),
    sa.Column('new_inn', sa.String(), nullable=True),
    sa.Column('date', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_id'), 'address', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_address_id'), table_name='address')
    op.drop_table('user_info_changes')
    # ### end Alembic commands ###
