"""make_region_country_mandatory

Revision ID: 56d6d814a61c
Revises: 78083c32609d
Create Date: 2023-12-24 18:24:27.114490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d6d814a61c'
down_revision: Union[str, None] = '78083c32609d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('region', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('region', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
