"""add_tg_to_user

Revision ID: 25ed2f2dd807
Revises: ec85d1f54c1e
Create Date: 2023-12-10 12:56:55.355478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ed2f2dd807'
down_revision: Union[str, None] = 'ec85d1f54c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('telegram_access_error', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telegram_access_error_shown', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_access_error_shown')
    op.drop_column('users', 'telegram_access_error')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###
