"""add_logs_table

Revision ID: 293e802c39fe
Revises: fec5dc4a33ca
Create Date: 2023-12-22 20:55:19.245598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "293e802c39fe"
down_revision: Union[str, None] = "fec5dc4a33ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "log_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("ERROR", "WARN", "INFO", "DEBUG", name="loglevel"),
            nullable=False,
        ),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("time", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_log_items_id"), "log_items", ["id"], unique=False)
    op.create_index(
        op.f("ix_log_items_request_id"), "log_items", ["request_id"], unique=False
    )
    op.create_index(
        op.f("ix_log_items_user_id"), "log_items", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_log_items_user_id"), table_name="log_items")
    op.drop_index(op.f("ix_log_items_request_id"), table_name="log_items")
    op.drop_index(op.f("ix_log_items_id"), table_name="log_items")
    op.drop_table("log_items")
    # ### end Alembic commands ###
