"""make_status_update_time_mandatory

Revision ID: 107a90c079f2
Revises: 19f5af5f7f48
Create Date: 2024-01-05 13:17:40.338419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107a90c079f2'
down_revision: Union[str, None] = '19f5af5f7f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
