"""add_order_urgency

Revision ID: b5f731857a17
Revises: 34b34c638afa
Create Date: 2024-01-12 08:52:55.563878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b5f731857a17"
down_revision: Union[str, None] = "34b34c638afa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("urgency", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "urgency")
    # ### end Alembic commands ###
