"""add_telegram_chats

Revision ID: 5a7b5ba3f726
Revises: 324266362cb3
Create Date: 2024-01-31 17:36:37.965902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a7b5ba3f726"
down_revision: Union[str, None] = "324266362cb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_chats",
        sa.Column("chat_uuid", sa.String(), nullable=False),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("chat_uuid"),
    )
    op.create_index(
        op.f("ix_telegram_chats_chat_uuid"),
        "telegram_chats",
        ["chat_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telegram_chats_telegram_chat_id"),
        "telegram_chats",
        ["telegram_chat_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_telegram_chats_telegram_chat_id"),
        table_name="telegram_chats",
    )
    op.drop_index(op.f("ix_telegram_chats_chat_uuid"), table_name="telegram_chats")
    op.drop_table("telegram_chats")
    # ### end Alembic commands ###
