"""add_orders_notifications

Revision ID: 34b34c638afa
Revises: 107a90c079f2
Create Date: 2024-01-05 14:24:50.513193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "34b34c638afa"
down_revision: Union[str, None] = "107a90c079f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders_notifications",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("order_last_status_change_time", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("order_id", "order_last_status_change_time"),
    )
    op.create_index(
        op.f("ix_orders_notifications_order_id"),
        "orders_notifications",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_orders_notifications_order_last_status_change_time"),
        "orders_notifications",
        ["order_last_status_change_time"],
        unique=False,
    )
    op.alter_column(
        "orders",
        "last_status_update_time",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "last_status_update_time",
        existing_type=sa.BIGINT(),
        nullable=True,
    )
    op.drop_index(
        op.f("ix_orders_notifications_order_last_status_change_time"),
        table_name="orders_notifications",
    )
    op.drop_index(
        op.f("ix_orders_notifications_order_id"),
        table_name="orders_notifications",
    )
    op.drop_table("orders_notifications")
    # ### end Alembic commands ###
