"""add_order_notes

Revision ID: 69e7cfee3cc1
Revises: b5f731857a17
Create Date: 2024-01-12 09:40:52.973509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e7cfee3cc1'
down_revision: Union[str, None] = 'b5f731857a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'notes')
    # ### end Alembic commands ###
