"""add_last_status_update_time

Revision ID: 19f5af5f7f48
Revises: e472ee7b3f85
Create Date: 2024-01-05 13:01:43.028381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "19f5af5f7f48"
down_revision: Union[str, None] = "e472ee7b3f85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("last_status_update_time", sa.BigInteger(), nullable=True),
    )
    op.create_index(
        op.f("ix_orders_last_status_update_time"),
        "orders",
        ["last_status_update_time"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_last_status_update_time"), table_name="orders")
    op.drop_column("orders", "last_status_update_time")
    # ### end Alembic commands ###
