"""add_files_to_messages

Revision ID: 324266362cb3
Revises: 3ea94967f08a
Create Date: 2024-01-22 21:38:43.966065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "324266362cb3"
down_revision: Union[str, None] = "3ea94967f08a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("extension", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("create_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(op.f("ix_files_code"), "files", ["code"], unique=False)
    op.add_column("order_messages", sa.Column("file_code", sa.String(), nullable=True))
    op.create_foreign_key(None, "order_messages", "files", ["file_code"], ["code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("None", "order_messages", type_="foreignkey")
    op.drop_column("order_messages", "file_code")
    op.drop_index(op.f("ix_files_code"), table_name="files")
    op.drop_table("files")
    # ### end Alembic commands ###
