"""add_order_messages

Revision ID: 3ea94967f08a
Revises: 69e7cfee3cc1
Create Date: 2024-01-20 11:13:28.284008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ea94967f08a"
down_revision: Union[str, None] = "69e7cfee3cc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guarantee_id", sa.String(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_role", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("date", sa.BigInteger(), nullable=False),
        sa.Column("is_viewed_by_master", sa.Boolean(), nullable=False),
        sa.Column("is_viewed_by_driver", sa.Boolean(), nullable=False),
        sa.Column("is_viewed_by_customer", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_messages_order_id"),
        "order_messages",
        ["order_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_messages_order_id"), table_name="order_messages")
    op.drop_table("order_messages")
    # ### end Alembic commands ###
