"""make_masters_ids_nullable

Revision ID: b0a296c9b2a8
Revises: 7497faf32ecb
Create Date: 2024-11-18 19:26:42.875708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0a296c9b2a8'
down_revision: Union[str, None] = '7497faf32ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'declined_masters_ids',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'declined_masters_ids',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
