"""add_chat_codes_to_user

Revision ID: edee169c6960
Revises: 5a7b5ba3f726
Create Date: 2024-01-31 19:46:16.857949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edee169c6960'
down_revision: Union[str, None] = '5a7b5ba3f726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_chats_codes', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_chats_codes')
    # ### end Alembic commands ###
