"""move_order_status_to_string

Revision ID: e472ee7b3f85
Revises: 02ea2b1ba2e7
Create Date: 2024-01-02 10:32:30.550792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e472ee7b3f85"
down_revision: Union[str, None] = "02ea2b1ba2e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "status",
        existing_type=postgresql.ENUM(
            "CREATED",
            "CALCULATING",
            "REVIEWING",
            "ACCEPTED",
            "COMPLETED",
            "CANCELED",
            name="orderstatus",
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "status",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "CREATED",
            "CALCULATING",
            "REVIEWING",
            "ACCEPTED",
            "COMPLETED",
            "CANCELED",
            name="orderstatus",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
